PRODUCT_VERSION_MAJOR := 1
PRODUCT_VERSION_MINOR := 1
PRODUCT_CODE_NAME := Tesla

AXIOM_PLATFORM_VERSION := 13
#tmp
AXIOM_RELEASE_TYPE := BETA

#TODO
ifneq ($(AXIOM_VERSION_APPEND_TIME_OF_DAY),true)
    AXIOM_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    AXIOM_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set AXIOM_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef AXIOM_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "AXIOM_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^AXIOM_||g')
        AXIOM_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(AXIOM_BUILDTYPE)),)
    AXIOM_BUILDTYPE := UNOFFICIAL
    AXIOM_EXTRAVERSION :=
endif

ifeq ($(AXIOM_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        AXIOM_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif
AXIOM_BUILDTYPE := BETA
AXIOM_EXTRAVERSION := -Tesla
AXIOM_VERSION_SUFFIX := $(AXIOM_BUILD_DATE)-$(AXIOM_BUILDTYPE)$(AXIOM_EXTRAVERSION)-$(AXIOM_BUILD)

# Internal version
AXIOM_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(AXIOM_VERSION_SUFFIX)

# Display version
AXIOM_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(PRODUCT_CODE_NAME)
